# Generated by Django 5.0.1 on 2024-01-28 06:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mylist",
            name="name",
        ),
        migrations.RemoveField(
            model_name="mylist",
            name="photo",
        ),
        migrations.RemoveField(
            model_name="mylist",
            name="url",
        ),
        migrations.RemoveField(
            model_name="mylist",
            name="video",
        ),
        migrations.RemoveField(
            model_name="reclist",
            name="name",
        ),
        migrations.RemoveField(
            model_name="reclist",
            name="photo",
        ),
        migrations.RemoveField(
            model_name="reclist",
            name="url",
        ),
        migrations.RemoveField(
            model_name="reclist",
            name="video",
        ),
        migrations.AddField(
            model_name="mylist",
            name="places",
            field=models.ManyToManyField(to="backend.place"),
        ),
        migrations.AddField(
            model_name="mylist",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="place",
            name="address_url",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="place",
            name="coordinate_url",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="place",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
        migrations.AddField(
            model_name="place",
            name="socialmedia_url",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="place",
            name="video",
            field=models.FileField(blank=True, null=True, upload_to=""),
        ),
        migrations.AddField(
            model_name="reclist",
            name="places",
            field=models.ManyToManyField(to="backend.place"),
        ),
    ]
