# Generated by Django 5.0.1 on 2024-01-28 06:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0002_remove_mylist_name_remove_mylist_photo_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="date",
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name="review",
            name="date",
            field=models.DateField(default=datetime.date.today),
        ),
    ]
